volumes:
  postgres-data:
    driver: local
  kestra-data:
    driver: local
  minio-data:
    driver: local

networks:
  app-network:
    driver: bridge

services:
  postgres:
    image: postgres:18
    networks:
      - app-network
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: kestra
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 10s
      retries: 10

  minio:
    image: minio/minio:RELEASE.2025-07-23T15-54-02Z
    command: server /data --console-address ":9001"
    networks:
      app-network:
        aliases:
          - minio
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    ports:
      - "9000:9000"
      - "9001:9001"

  kestra:
    image: kestra/kestra:latest
    networks:
      - app-network
    env_file:
      - .env_encoded
    pull_policy: always
    stop_grace_period: 6m
    user: "root"
    command: server standalone

    volumes:
      - kestra-data:/app/storage
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/kestra-wd:/tmp/kestra-wd
      - ./:/app/project

    environment:
      KESTRA_CONFIGURATION: |
        datasources:
          postgres:
            url: jdbc:postgresql://postgres:5432/kestra
            driverClassName: org.postgresql.Driver
            username: kestra
            password: k3str4

        kestra:
          repository:
            type: postgres

          storage:
            type: local
            local:
              base-path: "/app/storage"

          queue:
            type: postgres

          tasks:
            tmp-dir:
              path: /tmp/kestra-wd/tmp

          plugins:
            configurations:
              - type: io.kestra.plugin.scripts.runner.docker.Docker
                values:
                  volume-enabled: true

        url: http://localhost:8080/

    ports:
      - "8080:8080"

    depends_on:
      postgres:
        condition: service_started
      minio:
        condition: service_started