id: ventes_comptoir_coteaux
namespace: company.team

triggers:
  - id: monthly
    type: io.kestra.plugin.core.trigger.Schedule
    cron: "0 9 15 * *"
    timezone: Europe/Paris


tasks:

  - id: convert_to_parquet
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ventes-comptoir-coteaux
    pythonVersion: "3.12"

    env:
      S3_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "{{ secret('MINIO_ROOT_USER') }}"
      MINIO_ROOT_PASSWORD: "{{ secret('MINIO_ROOT_PASSWORD') }}"
      MINIO_BUCKET: "comptoir-coteaux"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "piplines_ventes_comptoir_coteaux_app-network"

    commands:
      - cd /app
      - PYTHONPATH=/app python -m scripts.convert_to_parquet

  - id: execute_sql
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ventes-comptoir-coteaux
    pythonVersion: "3.12"

    env:
      S3_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "{{ secret('MINIO_ROOT_USER') }}"
      MINIO_ROOT_PASSWORD: "{{ secret('MINIO_ROOT_PASSWORD') }}"
      MINIO_BUCKET: "comptoir-coteaux"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "piplines_ventes_comptoir_coteaux_app-network"

    commands:
      - cd /app
      - PYTHONPATH=/app python -m scripts.execute_sql

  - id: z_score
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ventes-comptoir-coteaux
    pythonVersion: "3.12"

    env:
      S3_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "{{ secret('MINIO_ROOT_USER') }}"
      MINIO_ROOT_PASSWORD: "{{ secret('MINIO_ROOT_PASSWORD') }}"
      MINIO_BUCKET: "comptoir-coteaux"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "piplines_ventes_comptoir_coteaux_app-network"

    commands:
      - cd /app
      - PYTHONPATH=/app python -m scripts.z_score

  - id: tests
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ventes-comptoir-coteaux
    pythonVersion: "3.12"

    env:
      S3_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "{{ secret('MINIO_ROOT_USER') }}"
      MINIO_ROOT_PASSWORD: "{{ secret('MINIO_ROOT_PASSWORD') }}"
      MINIO_BUCKET: "comptoir-coteaux"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "piplines_ventes_comptoir_coteaux_app-network"

    commands:
      - cd /app
      - PYTHONPATH=/app python -m tests.tests

  - id: test_sales
    type: io.kestra.plugin.scripts.python.Commands
    containerImage: ventes-comptoir-coteaux
    pythonVersion: "3.12"

    env:
      S3_ENDPOINT: "http://minio:9000"
      MINIO_ROOT_USER: "{{ secret('MINIO_ROOT_USER') }}"
      MINIO_ROOT_PASSWORD: "{{ secret('MINIO_ROOT_PASSWORD') }}"
      MINIO_BUCKET: "comptoir-coteaux"

    taskRunner:
      type: io.kestra.plugin.scripts.runner.docker.Docker
      networkMode: "piplines_ventes_comptoir_coteaux_app-network"

    commands:
      - cd /app
      - PYTHONPATH=/app python -m tests.test_sales